// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // This `url` is used ONLY by the Prisma CLI (migrate, studio, etc.), so it
  // must be the DIRECT (unpooled) connection — Migrate can't run through
  // Neon's pooler. The pooled DATABASE_URL is used separately, in app code,
  // when we construct the actual running PrismaClient with a driver adapter
  // (see src/models/ once that's built) — NOT here.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
