// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // used for normal app queries — goes through Neon's connection pooler
    url: process.env["DATABASE_URL"],
    // used only by Prisma CLI commands (migrations etc.) — bypasses the
    // pooler, since schema-changing operations need a direct connection
    directUrl: process.env["DIRECT_URL"],
  },
});
